name: Lint
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  tflint:
    name: Build & Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout source code
      - name: System info
        shell: bash
        run: |
          uname -a || true
          arch || true
          file $(which tflint) || true
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.tflint.hcl') }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2 
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
        env:
          TF_LOG: DEBUG
      - name: Debug plugin path
        shell: bash
        run: |
          ls -la ~/.tflint.d/plugins/github.com/terraform-linters/tflint-ruleset-aws/*/ || true
          file ~/.tflint.d/plugins/github.com/terraform-linters/tflint-ruleset-aws/*/tflint-ruleset-aws || true
      - name: Run TFLint
        run: tflint -f compact
